[path]
log_file = "py-recycle.log"
buffer_file = "buffer.db"
under_userprofile = true
buffer_bin = "py-recycle.bin"

[options]
silent = false
log = false
buffer = true

[start_up]
enable = true
message = "Loaded configurations from [loc].\nMove files to buffer bin for easy recovery using rc command."
